Repository mui/base-ui, pull requests merged in 2024-03, with the labels that each got.

#132 [core] Clean up API docs builder config
  .eslintrc.js
  docs/pages/base-ui/api/form-control.json
  docs/pages/base-ui/api/snackbar.json
  docs/pages/base-ui/api/textarea-autosize.json
  package.json
  packages/api-docs-builder-core/.eslintrc.js
  packages/api-docs-builder-core/baseUi/getBaseUiComponentInfo.skipped-test.ts
  packages/api-docs-builder-core/baseUi/getBaseUiHookInfo.skipped-test.ts
  packages/api-docs-builder-core/baseUi/migratedBaseComponents.ts
  packages/api-docs-builder-core/package.json
  packages/api-docs-builder-core/tsconfig.json
  pnpm-lock.yaml
  scripts/buildApiDocs/config/baseUi/generateApiLinks.ts
  scripts/buildApiDocs/config/baseUi/generateBaseUiApiPages.ts
  scripts/buildApiDocs/config/baseUi/getBaseUiComponentInfo.ts
  scripts/buildApiDocs/config/baseUi/getBaseUiHookInfo.ts
  scripts/buildApiDocs/config/baseUi/projectSettings.ts
  scripts/buildApiDocs/config/index.ts
  scripts/buildApiDocs/config/react-docgen.d.ts
  scripts/buildApiDocs/config/tsconfig.json
  scripts/buildApiDocs/index.ts
  scripts/buildApiDocs/tsconfig.json
Labels: core

#97 [core] Group MUI package updates
  renovate.json
Labels: dependencies

#177 [TextareaAutosize] Fix inline style not getting applied
  packages/mui-base/src/TextareaAutosize/TextareaAutosize.test.tsx
  packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx
Labels: bug 🐛, regression, component: TextareaAutosize

#136 [docs] Update the README
  README.md
Labels: docs

#138 [core] Replace old repo references
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/README.md
  docs/data/base/components/accordion/accordion.md
  docs/data/base/components/checkbox/checkbox.md
  docs/data/base/components/drawer/drawer.md
  docs/data/base/components/number-input/number-input.md
  docs/data/base/components/pagination/pagination.md
  docs/data/base/components/radio-group/radio-group.md
  docs/data/base/components/rating/rating.md
  docs/data/base/components/toggle-button-group/toggle-button-group.md
  docs/data/base/components/tooltip/tooltip.md
  docs/data/base/getting-started/overview/overview.md
  docs/data/base/getting-started/support/support.md
  docs/data/base/guides/next-js-app-router/next-js-app-router.md
  examples/base-ui-cra-ts/README.md
  examples/base-ui-cra/README.md
  examples/base-ui-nextjs-tailwind-ts/README.md
  examples/base-ui-vite-tailwind-ts/README.md
  examples/base-ui-vite-tailwind/README.md
  packages/mui-base/README.md
  packages/mui-base/package.json
Labels: core

#156 [core] Set docs port to 3005
  CONTRIBUTING.md
  docs/package.json
Labels: core, docs

#178 [core] Change when the no-response action is triggered
  .github/workflows/no-response.yml
Labels: core

#179 [test] Update karma config
  test/README.md
  test/karma.conf.js
  test/karma.conf.profile.js
Labels: test

#180 [core] Fix paths in API docs builder
  docs/package.json
  docs/pages/base-ui/api/badge.json
  docs/pages/base-ui/api/button.json
  docs/pages/base-ui/api/form-control.json
  docs/pages/base-ui/api/input.json
  docs/pages/base-ui/api/menu-button.json
  docs/pages/base-ui/api/menu-item.json
  docs/pages/base-ui/api/menu.json
  docs/pages/base-ui/api/modal.json
  docs/pages/base-ui/api/number-input.json
  docs/pages/base-ui/api/option-group.json
  docs/pages/base-ui/api/option.json
  docs/pages/base-ui/api/popper.json
  docs/pages/base-ui/api/popup.json
  docs/pages/base-ui/api/select.json
  docs/pages/base-ui/api/slider.json
  docs/pages/base-ui/api/snackbar.json
  docs/pages/base-ui/api/switch.json
  docs/pages/base-ui/api/tab-panel.json
  docs/pages/base-ui/api/tab.json
  docs/pages/base-ui/api/table-pagination.json
  docs/pages/base-ui/api/tabs-list.json
  docs/pages/base-ui/api/tabs.json
  docs/translations/api-docs-base/badge/badge.json
  docs/translations/api-docs-base/button/button.json
  docs/translations/api-docs-base/form-control/form-control.json
  docs/translations/api-docs-base/input/input.json
  docs/translations/api-docs-base/menu-button/menu-button.json
  docs/translations/api-docs-base/menu-item/menu-item.json
  docs/translations/api-docs-base/menu/menu.json
  docs/translations/api-docs-base/modal/modal.json
  docs/translations/api-docs-base/number-input/number-input.json
  docs/translations/api-docs-base/option-group/option-group.json
  docs/translations/api-docs-base/option/option.json
  docs/translations/api-docs-base/popper/popper.json
  docs/translations/api-docs-base/popup/popup.json
  docs/translations/api-docs-base/select/select.json
  docs/translations/api-docs-base/slider/slider.json
  docs/translations/api-docs-base/snackbar/snackbar.json
  docs/translations/api-docs-base/switch/switch.json
  docs/translations/api-docs-base/tab-panel/tab-panel.json
  docs/translations/api-docs-base/tab/tab.json
  docs/translations/api-docs-base/table-pagination/table-pagination.json
  docs/translations/api-docs-base/tabs-list/tabs-list.json
  docs/translations/api-docs-base/tabs/tabs.json
  package.json
  pnpm-lock.yaml
  scripts/buildApiDocs/config/baseUi/generateBaseUiApiPages.ts
  scripts/buildApiDocs/config/baseUi/getBaseUiComponentInfo.ts
  scripts/buildApiDocs/config/baseUi/getBaseUiHookInfo.ts
  scripts/buildApiDocs/config/baseUi/projectSettings.ts
Labels: scope: code-infra

#182 [core] Do not hoist the @mui/base package on Netlify
  netlify.toml
Labels: core

#184 [core] Update Codesandbox preview to use the dev packages
  docs/src/modules/sandbox/Dependencies.test.js
  docs/src/modules/sandbox/Dependencies.ts
Labels: core

#131 [core] Simplify build scripts
  babel.config.js
  packages/mui-base/package.json
  pnpm-lock.yaml
  scripts/build.mjs
  scripts/copyFiles.mjs
Labels: core

#190 [docs] Fix some Vale errors
  .circleci/config.yml
  .github/styles/Blog/BrandName.yml
  .github/styles/Blog/ComposedWords.yml
  .github/styles/Blog/NamingConventions.yml
  .github/styles/Blog/NoCompanyName.yml
  .github/styles/Blog/Typos.yml
  .github/styles/Vocab/accept.txt
  .github/styles/Vocab/reject.txt
  .gitignore
  .vale.ini
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  dangerfile.ts
  docs/README.md
  docs/data/base/components/badge/badge.md
  docs/data/base/components/button/button.md
  docs/data/base/components/focus-trap/focus-trap.md
  docs/data/base/components/form-control/form-control.md
  docs/data/base/components/input/input.md
  docs/data/base/components/menu/menu.md
  docs/data/base/components/no-ssr/no-ssr.md
  docs/data/base/components/select/select.md
  docs/data/base/components/snackbar/snackbar.md
  docs/data/base/components/tabs/tabs.md
  docs/data/base/getting-started/customization/customization.md
  docs/data/base/getting-started/quickstart/quickstart.md
  docs/data/base/getting-started/support/support.md
  docs/data/base/guides/next-js-app-router/next-js-app-router.md
  docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css.md
  docs/src/MuiPage.ts
  docs/src/modules/components/Ad.js
  docs/src/modules/components/AdCarbon.js
  docs/src/modules/components/AppNavDrawer.js
  docs/src/modules/components/AppNavDrawerItem.js
  docs/src/modules/components/AppTableOfContents.js
  docs/src/modules/components/MarkdownDocs.js
  docs/src/modules/components/MarkdownDocsV2.js
  docs/src/modules/components/MarkdownLinks.js
  docs/src/modules/components/Notifications.js
  docs/src/modules/sandbox/CodeSandbox.ts
  examples/base-ui-nextjs-tailwind-ts/README.md
  examples/base-ui-vite-tailwind-ts/README.md
  examples/base-ui-vite-tailwind/README.md
  packages/mui-base/README.md
  packages/mui-base/src/FocusTrap/FocusTrap.tsx
  packages/mui-base/src/useAutocomplete/useAutocomplete.js
  packages/mui-base/src/useCompound/useCompoundItem.ts
  packages/mui-base/src/useCompound/useCompoundParent.ts
  packages/mui-base/src/useList/useListItem.ts
  packages/mui-base/src/utils/useRootElementName.ts
  scripts/README.md
  scripts/buildApiDocs/config/baseUi/generateBaseUiApiPages.ts
  scripts/generateProptypes.ts
  test/README.md
  test/regressions/README.md
Labels: docs, scope: docs-infra

#202 [core] Adapt proptypes generator to project needs
  packages/mui-base/src/Input/Input.tsx
  packages/mui-base/src/TablePagination/TablePaginationActions.tsx
  packages/mui-base/src/TablePagination/TablePaginationActions.types.ts
  packages/mui-base/src/Transitions/CssAnimation.tsx
  packages/mui-base/src/Transitions/CssTransition.tsx
  scripts/generateProptypes.ts
Labels: core

#187 [test] Create the conformance test suite for the new API
  .eslintrc.js
  packages/mui-base/test/conformanceTests/className.tsx
  packages/mui-base/test/conformanceTests/propForwarding.tsx
  packages/mui-base/test/conformanceTests/refForwarding.tsx
  packages/mui-base/test/conformanceTests/renderProp.tsx
  packages/mui-base/test/conformanceTests/utils.ts
  packages/mui-base/test/describeConformance.tsx
  packages/mui-base/test/describeConformanceUnstyled.tsx
Labels: test

#208 [core] Disable updating packages to incompatible versions
  renovate.json
Labels: core, dependencies

#210 [core] Disable updating packages to incompatible versions (part 2)
  renovate.json
Labels: core, dependencies

#203 [core] Allow lockflile changes when building with React next
  .circleci/config.yml
  packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
Labels: core

#246 [core] Fix dedupe check on CI
  .circleci/config.yml
Labels: core

#207 [core] Use TS project references to typecheck all projects
  .circleci/config.yml
  docs/data/base/components/select/UnstyledSelectIntroduction/css/index.js
  docs/data/base/components/select/UnstyledSelectIntroduction/css/index.tsx
  docs/package.json
  docs/pages/base-ui/api/use-autocomplete.json
  docs/tsconfig.json
  package.json
  packages/mui-base/package.json
  packages/mui-base/src/index.js
  packages/mui-base/src/index.ts
  packages/mui-base/src/useAutocomplete/index.d.ts
  packages/mui-base/src/useAutocomplete/index.js
  packages/mui-base/src/useAutocomplete/index.ts
  packages/mui-base/src/useAutocomplete/useAutocomplete.ts
  packages/mui-base/src/useAutocomplete/useAutocomplete.types.ts
  packages/mui-base/src/utils/useSlotProps.test.tsx
  packages/mui-base/test/typescript/moduleAugmentation/selectComponentsProps.spec.tsx
  packages/mui-base/test/typescript/moduleAugmentation/sliderComponentsProps.spec.tsx
  scripts/buildApiDocs/config/baseUi/projectSettings.ts
  scripts/buildApiDocs/config/tsconfig.json
  scripts/coreTypeScriptProjects.js
  tsconfig.typecheck.json
Labels: core

#244 [core] Remove unnecessary stylelint-processor-styled-components
  package.json
  pnpm-lock.yaml
Labels: core, dependencies

#247 [core] Correct the Readme file
  README.md
Labels: core
