Repository mui/base-ui, pull requests merged in 2024-04, with the labels that each got.

#243 [core] Create `mergeReactProps` utility
  docs/pages/base-ui/api/use-switch.json
  packages/mui-base/src/Switch/Switch.tsx
  packages/mui-base/src/Switch/Switch.types.ts
  packages/mui-base/src/useSwitch/useSwitch.ts
  packages/mui-base/src/useSwitch/useSwitch.types.ts
  packages/mui-base/src/utils/BaseUI.types.ts
  packages/mui-base/src/utils/mergeReactProps.test.ts
  packages/mui-base/src/utils/mergeReactProps.ts
Labels: core

#159 [Checkbox] Component and Hook
  docs/data/base/components/checkbox/UnstyledCheckboxIndeterminate.js
  docs/data/base/components/checkbox/UnstyledCheckboxIndeterminate.tsx
  docs/data/base/components/checkbox/UnstyledCheckboxIndeterminate.tsx.preview
  docs/data/base/components/checkbox/UnstyledCheckboxIndeterminateGroup.js
  docs/data/base/components/checkbox/UnstyledCheckboxIndeterminateGroup.tsx
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/css/index.js
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/css/index.tsx
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/system/index.js
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/system/index.tsx
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/tailwind/index.js
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/tailwind/index.tsx
  docs/data/base/components/checkbox/UnstyledCheckboxIntroduction/tailwind/index.tsx.preview
  docs/data/base/components/checkbox/checkbox.md
  docs/data/base/pages.ts
  docs/data/base/pagesApi.js
  docs/pages/base-ui/api/checkbox-indicator.json
  docs/pages/base-ui/api/checkbox.json
  docs/pages/base-ui/api/use-checkbox.json
  docs/pages/base-ui/react-checkbox/[docsTab]/index.js
  docs/translations/api-docs-base/checkbox-indicator/checkbox-indicator.json
  docs/translations/api-docs-base/checkbox/checkbox.json
  docs/translations/api-docs/use-checkbox/use-checkbox.json
  docs/translations/translations.json
  packages/mui-base/src/Checkbox/Checkbox.test.tsx
  packages/mui-base/src/Checkbox/Checkbox.tsx
  packages/mui-base/src/Checkbox/Checkbox.types.ts
  packages/mui-base/src/Checkbox/CheckboxContext.ts
  packages/mui-base/src/Checkbox/CheckboxIndicator.test.tsx
  packages/mui-base/src/Checkbox/CheckboxIndicator.tsx
  packages/mui-base/src/Checkbox/index.ts
  packages/mui-base/src/Checkbox/utils.ts
  packages/mui-base/src/index.ts
  packages/mui-base/src/useCheckbox/index.ts
  packages/mui-base/src/useCheckbox/useCheckbox.ts
  packages/mui-base/src/useCheckbox/useCheckbox.types.ts
  packages/mui-base/src/utils/mergeReactProps.ts
Labels: component: checkbox

#266 [core] Adjust conformance tests to support portals
  packages/mui-base/test/conformanceTests/className.tsx
  packages/mui-base/test/conformanceTests/renderProp.tsx
Labels: core

#292 [docs] Add Checkbox and Number Field images
  docs/public/static/base-ui/react-components/autocomplete-dark.png
  docs/public/static/base-ui/react-components/autocomplete-light.png
  docs/public/static/base-ui/react-components/badge-dark.png
  docs/public/static/base-ui/react-components/badge-light.png
  docs/public/static/base-ui/react-components/button-dark.png
  docs/public/static/base-ui/react-components/button-light.png
  docs/public/static/base-ui/react-components/checkbox-dark.png
  docs/public/static/base-ui/react-components/checkbox-light.png
  docs/public/static/base-ui/react-components/click-away-dark.png
  docs/public/static/base-ui/react-components/click-away-light.png
  docs/public/static/base-ui/react-components/focus-trap-dark.png
  docs/public/static/base-ui/react-components/focus-trap-light.png
  docs/public/static/base-ui/react-components/form-control-dark.png
  docs/public/static/base-ui/react-components/form-control-light.png
  docs/public/static/base-ui/react-components/input-dark.png
  docs/public/static/base-ui/react-components/input-light.png
  docs/public/static/base-ui/react-components/menu-dark.png
  docs/public/static/base-ui/react-components/menu-light.png
  docs/public/static/base-ui/react-components/modal-dark.png
  docs/public/static/base-ui/react-components/modal-light.png
  docs/public/static/base-ui/react-components/no-ssr-dark.png
  docs/public/static/base-ui/react-components/no-ssr-light.png
  docs/public/static/base-ui/react-components/number-field-dark.png
  docs/public/static/base-ui/react-components/number-field-light.png
  docs/public/static/base-ui/react-components/number-input-dark.png
  docs/public/static/base-ui/react-components/number-input-light.png
  docs/public/static/base-ui/react-components/pagination-dark.png
  docs/public/static/base-ui/react-components/pagination-light.png
  docs/public/static/base-ui/react-components/popper-dark.png
  docs/public/static/base-ui/react-components/popper-light.png
  docs/public/static/base-ui/react-components/portal-dark.png
  docs/public/static/base-ui/react-components/portal-light.png
  docs/public/static/base-ui/react-components/select-dark.png
  docs/public/static/base-ui/react-components/select-light.png
  docs/public/static/base-ui/react-components/slider-dark.png
  docs/public/static/base-ui/react-components/slider-light.png
  docs/public/static/base-ui/react-components/snackbar-dark.png
  docs/public/static/base-ui/react-components/snackbar-light.png
  docs/public/static/base-ui/react-components/switch-dark.png
  docs/public/static/base-ui/react-components/switch-light.png
  docs/public/static/base-ui/react-components/tabs-dark.png
  docs/public/static/base-ui/react-components/tabs-light.png
  docs/public/static/base-ui/react-components/textarea-dark.png
  docs/public/static/base-ui/react-components/textarea-light.png
  docs/src/modules/components/BaseUIComponents.js
Labels: docs

#288 [core] Exclude legacy components from the package
  docs/data/base/pages.ts
  docs/pages/base-ui/api/use-autocomplete.json
  docs/pages/base-ui/api/use-badge.json
  docs/pages/base-ui/api/use-button.json
  docs/pages/base-ui/api/use-dropdown.json
  docs/pages/base-ui/api/use-form-control-context.json
  docs/pages/base-ui/api/use-input.json
  docs/pages/base-ui/api/use-menu-button.json
  docs/pages/base-ui/api/use-menu-item.json
  docs/pages/base-ui/api/use-menu.json
  docs/pages/base-ui/api/use-modal.json
  docs/pages/base-ui/api/use-option.json
  docs/pages/base-ui/api/use-select.json
  docs/pages/base-ui/api/use-slider.json
  docs/pages/base-ui/api/use-snackbar.json
  docs/pages/base-ui/api/use-tab-panel.json
  docs/pages/base-ui/api/use-tab.json
  docs/pages/base-ui/api/use-tabs-list.json
  docs/pages/base-ui/api/use-tabs.json
  docs/src/modules/components/BaseUIComponents.js
  docs/translations/api-docs/use-autocomplete/use-autocomplete.json
  docs/translations/api-docs/use-badge/use-badge.json
  docs/translations/api-docs/use-button/use-button.json
  docs/translations/api-docs/use-dropdown/use-dropdown.json
  docs/translations/api-docs/use-form-control-context/use-form-control-context.json
  docs/translations/api-docs/use-input/use-input.json
  docs/translations/api-docs/use-menu-button/use-menu-button.json
  docs/translations/api-docs/use-menu-item/use-menu-item.json
  docs/translations/api-docs/use-menu/use-menu.json
  docs/translations/api-docs/use-modal/use-modal.json
  docs/translations/api-docs/use-number-input/use-number-input.json
  docs/translations/api-docs/use-option/use-option.json
  docs/translations/api-docs/use-select/use-select.json
  docs/translations/api-docs/use-slider/use-slider.json
  docs/translations/api-docs/use-snackbar/use-snackbar.json
  docs/translations/api-docs/use-tab-panel/use-tab-panel.json
  docs/translations/api-docs/use-tab/use-tab.json
  docs/translations/api-docs/use-tabs-list/use-tabs-list.json
  docs/translations/api-docs/use-tabs/use-tabs.json
  docs/translations/translations.json
  packages/mui-base/package.json
  packages/mui-base/src/index.ts
Labels: core

#188 [code-infra] Use @mui/docs from npm
  docs/package.json
  package.json
  pnpm-lock.yaml
Labels: scope: code-infra

#227 [core][Slider] Ref immutable consistency
  packages/mui-base/src/useSlider/useSlider.ts
Labels: core, typescript

#295 [core] Fix license entity reference
  LICENSE
Labels: core

#296 [NumberField] Add `UseNumberFieldParameters` type
  docs/pages/base-ui/api/number-field.json
  docs/pages/base-ui/api/use-number-field.json
  docs/translations/api-docs-base/number-field/number-field.json
  docs/translations/api-docs/use-number-field/use-number-field.json
  packages/mui-base/src/NumberField/NumberField.tsx
  packages/mui-base/src/NumberField/NumberField.types.ts
  packages/mui-base/src/useNumberField/useNumberField.ts
  packages/mui-base/src/useNumberField/useNumberField.types.ts
Labels: component: number field

#291 [release] 1.0.0-alpha.0
  CHANGELOG.md
Labels: release

#319 [core] Change the references to the Material UI repo in the releaseTag script
  scripts/releaseTag.mjs
Labels: core

#322 [test] Update Karma config
  packages/mui-base/src/Select/Select.test.tsx
  pnpm-lock.yaml
  test/karma.conf.js
  test/package.json
Labels: test

#317 [NumberField] Fix failing browser tests
  packages/mui-base/src/NumberField/NumberFieldScrubArea.test.tsx
  packages/mui-base/src/NumberField/NumberFieldScrubAreaCursor.test.tsx
  packages/mui-base/src/useNumberField/useScrub.ts
Labels: component: number field

#320 [core] Describe how to publish the docs
  scripts/README.md
Labels: core

#321 [website] Use absolute URLs for non-Base pages
  docs/src/route.ts
Labels: website

#323 [docs] Remove or hide pages describing the old API
  docs/data/base/getting-started/overview/overview.md
  docs/data/base/getting-started/quickstart/quickstart.md
  docs/data/base/getting-started/support/support.md
  docs/data/base/getting-started/usage/usage.md
  docs/data/base/guides/next-js-app-router/next-js-app-router.md
  docs/data/base/pages.ts
  docs/pages/base-ui.tsx
  docs/src/components/productBaseUI/BaseUICustomization.tsx
  docs/translations/translations.json
Labels: docs

#324 [core] Clean up unnecessary files
  .tidelift.yml
  crowdin.yml
  patches/@mui__docs@5.15.14.patch
  vercel.json
Labels: core

#334 [core] Use the root dependency
  docs/package.json
  pnpm-lock.yaml
Labels: core

#333 [core] Remove redundant Next.js config
  docs/next.config.mjs
Labels: dependencies, on hold

#332 [core] Remove legacy dependencies and settings
  babel.config.js
  docs/babel.config.js
  docs/package.json
  package.json
  pnpm-lock.yaml
  scripts/buildApiDocs/config/generateApiLinks.ts
  scripts/buildApiDocs/config/generateBaseUiApiPages.ts
  scripts/buildApiDocs/config/getBaseUiComponentInfo.ts
  scripts/buildApiDocs/config/getBaseUiHookInfo.ts
  scripts/buildApiDocs/config/getComponentImports.ts
  scripts/buildApiDocs/config/index.ts
  scripts/buildApiDocs/config/projectSettings.ts
  scripts/buildApiDocs/index.ts
  scripts/buildApiDocs/react-docgen.d.ts
  scripts/buildApiDocs/tsconfig.json
  tsconfig.json
Labels: core

#354 [core] Update @mui deps to next
  docs/data/base/components/number-field/number-field.md
  docs/package.json
  package.json
  pnpm-lock.yaml
Labels: core

#352 [code-infra] Rely on @mui/monorepo/.eslintrc
  .eslintrc.js
Labels: scope: code-infra

#377 [core] Config cleanup
  .browserslistrc
  .circleci/config.yml
  .eslintignore
  .gitignore
  babel.config.js
  docs/babel.config.js
  docs/next.config.mjs
  pnpm-workspace.yaml
Labels: core
